// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AtiendePor struct {
	IDMedico         int32  `json:"id_medico"`
	ObraSocialNombre string `json:"obra_social_nombre"`
}

type Medico struct {
	IDMedico     int32  `json:"id_medico"`
	NroMatricula int32  `json:"nro_matricula"`
	Especialidad string `json:"especialidad"`
}

type ObraSocial struct {
	Nombre string `json:"nombre"`
}

type Paciente struct {
	IDPaciente  int32          `json:"id_paciente"`
	ObraSocial  sql.NullString `json:"obra_social"`
	NroAfiliado sql.NullString `json:"nro_afiliado"`
}

type Turno struct {
	IDTurno    int32     `json:"id_turno"`
	IDMedico   int32     `json:"id_medico"`
	IDPaciente int32     `json:"id_paciente"`
	Estado     string    `json:"estado"`
	Fecha      time.Time `json:"fecha"`
	Hora       time.Time `json:"hora"`
}

type Usuario struct {
	ID              int32     `json:"id"`
	Dni             string    `json:"dni"`
	Nombre          string    `json:"nombre"`
	Apellido        string    `json:"apellido"`
	Sexo            string    `json:"sexo"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
	Email           string    `json:"email"`
	Telefono        string    `json:"telefono"`
	Rol             string    `json:"rol"`
}
