// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: obra_social.sql

package db

import (
	"context"
)

const crearObraSocial = `-- name: CrearObraSocial :one
INSERT INTO obra_social (nombre)
VALUES ($1) 
RETURNING nombre
`

func (q *Queries) CrearObraSocial(ctx context.Context, nombre string) (string, error) {
	row := q.db.QueryRowContext(ctx, crearObraSocial, nombre)
	err := row.Scan(&nombre)
	return nombre, err
}

const eliminarObraSocial = `-- name: EliminarObraSocial :execrows
DELETE FROM obra_social
WHERE nombre = $1
`

func (q *Queries) EliminarObraSocial(ctx context.Context, nombre string) (int64, error) {
	result, err := q.db.ExecContext(ctx, eliminarObraSocial, nombre)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
